export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export interface StickerEntry {
  char: string;
  name: string;
  keywords: string[];
}

export interface StickerPack {
  id: string;
  label: string;
  icon: string;
  stickers: StickerEntry[];
}

// ─── Emoji Categories ────────────────────────────────────────────────────────

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['happy', 'smile', 'grin', 'joy'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile', 'excited'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'smile', 'joy'] },
      { char: '😁', name: 'beaming face with smiling eyes', keywords: ['happy', 'grin', 'smile'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy', 'haha'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['nervous', 'awkward', 'sweat'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'funny', 'lol'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'funny', 'lol'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy', 'pleased'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm', 'irony'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt', 'joke'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['happy', 'blush', 'cute'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'good'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore', 'heart', 'cute'] },
      { char: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'heart', 'adore'] },
      { char: '🤩', name: 'star-struck', keywords: ['star', 'excited', 'wow', 'amazing'] },
      { char: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'heart', 'blow'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss', 'love'] },
      { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'love'] },
      { char: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'smile'] },
      { char: '🥲', name: 'smiling face with tear', keywords: ['happy', 'sad', 'tear', 'bittersweet'] },
      { char: '😋', name: 'face savoring food', keywords: ['yum', 'delicious', 'food', 'taste'] },
      { char: '😛', name: 'face with tongue', keywords: ['silly', 'tongue', 'tease'] },
      { char: '😜', name: 'winking face with tongue', keywords: ['silly', 'wink', 'tongue', 'playful'] },
      { char: '🤪', name: 'zany face', keywords: ['silly', 'crazy', 'wild', 'fun'] },
      { char: '😝', name: 'squinting face with tongue', keywords: ['silly', 'tongue', 'playful'] },
      { char: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'dollar'] },
      { char: '🤗', name: 'smiling face with open hands', keywords: ['hug', 'warm', 'embrace'] },
      { char: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle', 'secret'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'secret', 'shhh'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'pondering', 'curious'] },
      { char: '🤐', name: 'zipper-mouth face', keywords: ['silent', 'quiet', 'secret', 'zip'] },
      { char: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'suspicious', 'doubt'] },
      { char: '😐', name: 'neutral face', keywords: ['neutral', 'blank', 'meh'] },
      { char: '😑', name: 'expressionless face', keywords: ['expressionless', 'blank', 'meh'] },
      { char: '😶', name: 'face without mouth', keywords: ['silent', 'no words', 'speechless'] },
      { char: '😏', name: 'smirking face', keywords: ['smirk', 'smug', 'sly'] },
      { char: '😒', name: 'unamused face', keywords: ['unamused', 'bored', 'unimpressed'] },
      { char: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'whatever', 'bored'] },
      { char: '😬', name: 'grimacing face', keywords: ['grimace', 'awkward', 'nervous'] },
      { char: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio', 'dishonest'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'pensive', 'down'] },
      { char: '😪', name: 'sleepy face', keywords: ['sleepy', 'tired', 'snot'] },
      { char: '🤤', name: 'drooling face', keywords: ['drool', 'hungry', 'desire'] },
      { char: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'] },
      { char: '😷', name: 'face with medical mask', keywords: ['sick', 'mask', 'ill', 'covid'] },
      { char: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'ill'] },
      { char: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured', 'bandage'] },
      { char: '🤢', name: 'nauseated face', keywords: ['sick', 'nausea', 'gross'] },
      { char: '🤧', name: 'sneezing face', keywords: ['sneeze', 'sick', 'cold'] },
      { char: '🥵', name: 'hot face', keywords: ['hot', 'warm', 'fever', 'heat'] },
      { char: '🥶', name: 'cold face', keywords: ['cold', 'freeze', 'frozen'] },
      { char: '🥴', name: 'woozy face', keywords: ['drunk', 'dizzy', 'woozy'] },
      { char: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead', 'knocked out'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked', 'wow', 'amazing'] },
      { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'western', 'hat'] },
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday', 'woo'] },
      { char: '🥸', name: 'disguised face', keywords: ['disguise', 'glasses', 'incognito'] },
      { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses', 'awesome'] },
      { char: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses', 'smart'] },
      { char: '🧐', name: 'face with monocle', keywords: ['curious', 'monocle', 'thinking'] },
      { char: '😕', name: 'confused face', keywords: ['confused', 'hmm', 'unsure'] },
      { char: '😟', name: 'worried face', keywords: ['worried', 'anxious', 'nervous'] },
      { char: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown', 'unhappy'] },
      { char: '☹️', name: 'frowning face', keywords: ['sad', 'frown', 'unhappy'] },
      { char: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow', 'open', 'shock'] },
      { char: '😯', name: 'hushed face', keywords: ['surprised', 'hushed', 'shocked'] },
      { char: '😲', name: 'astonished face', keywords: ['astonished', 'shocked', 'wow'] },
      { char: '😳', name: 'flushed face', keywords: ['embarrassed', 'flushed', 'blush'] },
      { char: '🥺', name: 'pleading face', keywords: ['pleading', 'puppy eyes', 'please', 'cute'] },
      { char: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'surprised', 'frown'] },
      { char: '😧', name: 'anguished face', keywords: ['anguished', 'shocked', 'horrified'] },
      { char: '😨', name: 'fearful face', keywords: ['fear', 'scared', 'fearful'] },
      { char: '😰', name: 'anxious face with sweat', keywords: ['anxious', 'nervous', 'cold sweat'] },
      { char: '😥', name: 'sad but relieved face', keywords: ['sad', 'relieved', 'sweat'] },
      { char: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear', 'weep'] },
      { char: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'sad', 'tears'] },
      { char: '😱', name: 'face screaming in fear', keywords: ['scream', 'fear', 'scared', 'horror'] },
      { char: '😖', name: 'confounded face', keywords: ['confounded', 'confused', 'frustrated'] },
      { char: '😣', name: 'persevering face', keywords: ['struggle', 'persevere', 'straining'] },
      { char: '😞', name: 'disappointed face', keywords: ['disappointed', 'sad', 'down'] },
      { char: '😓', name: 'downcast face with sweat', keywords: ['sweat', 'sad', 'hard work'] },
      { char: '😩', name: 'weary face', keywords: ['weary', 'tired', 'exhausted'] },
      { char: '😫', name: 'tired face', keywords: ['tired', 'exhausted', 'weary'] },
      { char: '🥱', name: 'yawning face', keywords: ['yawn', 'bored', 'tired', 'sleepy'] },
      { char: '😤', name: 'face with steam from nose', keywords: ['angry', 'frustrated', 'triumph'] },
      { char: '😡', name: 'enraged face', keywords: ['angry', 'rage', 'mad'] },
      { char: '😠', name: 'angry face', keywords: ['angry', 'mad', 'upset'] },
      { char: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swear', 'cursing'] },
      { char: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischief'] },
      { char: '👿', name: 'angry face with horns', keywords: ['devil', 'evil', 'angry'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'death', 'skull', 'skeleton'] },
      { char: '☠️', name: 'skull and crossbones', keywords: ['dead', 'poison', 'pirate', 'danger'] },
      { char: '💩', name: 'pile of poo', keywords: ['poop', 'funny', 'crap'] },
      { char: '🤡', name: 'clown face', keywords: ['clown', 'joker', 'circus'] },
      { char: '👻', name: 'ghost', keywords: ['ghost', 'spooky', 'halloween'] },
      { char: '👽', name: 'alien', keywords: ['alien', 'space', 'ufo', 'extraterrestrial'] },
      { char: '🤖', name: 'robot', keywords: ['robot', 'bot', 'ai', 'tech'] },
    ]
  },
  {
    id: 'people',
    label: 'People & Body',
    icon: '👋',
    emojis: [
      { char: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'hi', 'bye'] },
      { char: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop', 'raised'] },
      { char: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five', 'fingers'] },
      { char: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'] },
      { char: '🖖', name: 'vulcan salute', keywords: ['vulcan', 'spock', 'star trek'] },
      { char: '👌', name: 'ok hand', keywords: ['ok', 'okay', 'perfect', 'fine'] },
      { char: '🤌', name: 'pinched fingers', keywords: ['italian', 'chef kiss', 'fingers'] },
      { char: '🤏', name: 'pinching hand', keywords: ['small', 'tiny', 'pinch'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'v sign'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck', 'fingers crossed', 'hope'] },
      { char: '🤟', name: 'love-you gesture', keywords: ['love', 'ily', 'sign'] },
      { char: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal', 'horns'] },
      { char: '🤙', name: 'call me hand', keywords: ['call', 'phone', 'shaka'] },
      { char: '👈', name: 'backhand index pointing left', keywords: ['point', 'left', 'direction'] },
      { char: '👉', name: 'backhand index pointing right', keywords: ['point', 'right', 'direction'] },
      { char: '👆', name: 'backhand index pointing up', keywords: ['point', 'up', 'above'] },
      { char: '🖕', name: 'middle finger', keywords: ['middle finger', 'rude'] },
      { char: '👇', name: 'backhand index pointing down', keywords: ['point', 'down', 'below'] },
      { char: '☝️', name: 'index pointing up', keywords: ['one', 'point', 'up'] },
      { char: '👍', name: 'thumbs up', keywords: ['like', 'approve', 'yes', 'thumbs up', 'good'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'thumbs down', 'bad'] },
      { char: '✊', name: 'raised fist', keywords: ['fist', 'punch', 'power'] },
      { char: '👊', name: 'oncoming fist', keywords: ['punch', 'fist bump', 'hit'] },
      { char: '🤛', name: 'left-facing fist', keywords: ['fist bump', 'left'] },
      { char: '🤜', name: 'right-facing fist', keywords: ['fist bump', 'right'] },
      { char: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo', 'well done'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise', 'hands up', 'yes'] },
      { char: '🤲', name: 'palms up together', keywords: ['prayer', 'please', 'hands'] },
      { char: '🤝', name: 'handshake', keywords: ['handshake', 'deal', 'agreement'] },
      { char: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks', 'namaste', 'hope'] },
      { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'flex', 'power'] },
      { char: '🦾', name: 'mechanical arm', keywords: ['robot', 'arm', 'prosthetic', 'cyborg'] },
      { char: '🦵', name: 'leg', keywords: ['leg', 'kick', 'limb'] },
      { char: '🦶', name: 'foot', keywords: ['foot', 'kick', 'stomp'] },
      { char: '👂', name: 'ear', keywords: ['ear', 'listen', 'hear'] },
      { char: '👃', name: 'nose', keywords: ['nose', 'smell'] },
      { char: '🧠', name: 'brain', keywords: ['brain', 'smart', 'intelligence', 'mind'] },
      { char: '🫁', name: 'lungs', keywords: ['lungs', 'breath', 'breathe'] },
      { char: '🦷', name: 'tooth', keywords: ['tooth', 'dentist', 'teeth'] },
      { char: '👅', name: 'tongue', keywords: ['tongue', 'lick', 'taste'] },
      { char: '👁️', name: 'eye', keywords: ['eye', 'see', 'look', 'watch'] },
      { char: '👀', name: 'eyes', keywords: ['eyes', 'look', 'see', 'watch', 'stare'] },
      { char: '👤', name: 'bust in silhouette', keywords: ['person', 'user', 'profile', 'account'] },
      { char: '👥', name: 'busts in silhouette', keywords: ['people', 'users', 'group', 'team'] },
      { char: '🧑', name: 'person', keywords: ['person', 'human', 'individual'] },
      { char: '👦', name: 'boy', keywords: ['boy', 'child', 'male', 'kid'] },
      { char: '👧', name: 'girl', keywords: ['girl', 'child', 'female', 'kid'] },
      { char: '🧒', name: 'child', keywords: ['child', 'kid', 'young'] },
      { char: '👨', name: 'man', keywords: ['man', 'male', 'adult'] },
      { char: '👩', name: 'woman', keywords: ['woman', 'female', 'adult'] },
      { char: '🧓', name: 'older person', keywords: ['old', 'elder', 'senior'] },
      { char: '👴', name: 'old man', keywords: ['old', 'grandfather', 'elder'] },
      { char: '👵', name: 'old woman', keywords: ['old', 'grandmother', 'elder'] },
      { char: '🧑‍💻', name: 'technologist', keywords: ['developer', 'coder', 'programmer', 'tech'] },
      { char: '👨‍💻', name: 'man technologist', keywords: ['developer', 'coder', 'programmer'] },
      { char: '👩‍💻', name: 'woman technologist', keywords: ['developer', 'coder', 'programmer'] },
      { char: '🧑‍🏫', name: 'teacher', keywords: ['teacher', 'instructor', 'professor'] },
      { char: '🧑‍🎨', name: 'artist', keywords: ['artist', 'creative', 'design', 'painter'] },
      { char: '💃', name: 'woman dancing', keywords: ['dance', 'party', 'flamenco'] },
      { char: '🕺', name: 'man dancing', keywords: ['dance', 'party', 'move'] },
      { char: '🧘', name: 'person in lotus position', keywords: ['meditate', 'yoga', 'calm'] },
      { char: '🤸', name: 'person cartwheeling', keywords: ['gymnastics', 'cartwheel', 'flexible'] },
    ]
  },
  {
    id: 'animals',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { char: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet', 'cute'] },
      { char: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet', 'cute'] },
      { char: '🐭', name: 'mouse face', keywords: ['mouse', 'rodent', 'small'] },
      { char: '🐹', name: 'hamster', keywords: ['hamster', 'pet', 'cute'] },
      { char: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny', 'cute', 'easter'] },
      { char: '🦊', name: 'fox', keywords: ['fox', 'clever', 'cunning'] },
      { char: '🐻', name: 'bear', keywords: ['bear', 'brown', 'animal'] },
      { char: '🐼', name: 'panda', keywords: ['panda', 'cute', 'bear', 'china'] },
      { char: '🐨', name: 'koala', keywords: ['koala', 'australia', 'bear', 'cute'] },
      { char: '🐯', name: 'tiger face', keywords: ['tiger', 'wild', 'striped'] },
      { char: '🦁', name: 'lion', keywords: ['lion', 'king', 'wild', 'brave'] },
      { char: '🐮', name: 'cow face', keywords: ['cow', 'moo', 'farm'] },
      { char: '🐷', name: 'pig face', keywords: ['pig', 'oink', 'farm'] },
      { char: '🐸', name: 'frog', keywords: ['frog', 'green', 'jump'] },
      { char: '🐵', name: 'monkey face', keywords: ['monkey', 'ape', 'banana'] },
      { char: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'see no evil', 'blind'] },
      { char: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'hear no evil'] },
      { char: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'speak no evil', 'quiet'] },
      { char: '🐔', name: 'chicken', keywords: ['chicken', 'bird', 'farm'] },
      { char: '🐧', name: 'penguin', keywords: ['penguin', 'cold', 'cute', 'bird'] },
      { char: '🐦', name: 'bird', keywords: ['bird', 'tweet', 'fly'] },
      { char: '🦆', name: 'duck', keywords: ['duck', 'quack', 'bird'] },
      { char: '🦅', name: 'eagle', keywords: ['eagle', 'bird', 'freedom', 'powerful'] },
      { char: '🦉', name: 'owl', keywords: ['owl', 'wise', 'night', 'bird'] },
      { char: '🦇', name: 'bat', keywords: ['bat', 'night', 'halloween'] },
      { char: '🐺', name: 'wolf', keywords: ['wolf', 'howl', 'wild'] },
      { char: '🐗', name: 'boar', keywords: ['boar', 'pig', 'wild'] },
      { char: '🐴', name: 'horse face', keywords: ['horse', 'pony', 'neigh'] },
      { char: '🦄', name: 'unicorn', keywords: ['unicorn', 'magical', 'rainbow', 'fantasy'] },
      { char: '🐝', name: 'honeybee', keywords: ['bee', 'honey', 'sting', 'insect'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly', 'beautiful', 'insect', 'transform'] },
      { char: '🐛', name: 'bug', keywords: ['bug', 'caterpillar', 'worm', 'insect'] },
      { char: '🐢', name: 'turtle', keywords: ['turtle', 'slow', 'shell', 'reptile'] },
      { char: '🐍', name: 'snake', keywords: ['snake', 'slithery', 'reptile'] },
      { char: '🦖', name: 'T-rex', keywords: ['dinosaur', 'trex', 'prehistoric'] },
      { char: '🦕', name: 'sauropod', keywords: ['dinosaur', 'prehistoric'] },
      { char: '🐙', name: 'octopus', keywords: ['octopus', 'tentacles', 'sea'] },
      { char: '🦈', name: 'shark', keywords: ['shark', 'ocean', 'scary', 'fish'] },
      { char: '🐬', name: 'dolphin', keywords: ['dolphin', 'ocean', 'smart'] },
      { char: '🐳', name: 'spouting whale', keywords: ['whale', 'ocean', 'big'] },
      { char: '🦓', name: 'zebra', keywords: ['zebra', 'stripes', 'africa'] },
      { char: '🦒', name: 'giraffe', keywords: ['giraffe', 'tall', 'africa'] },
      { char: '🦘', name: 'kangaroo', keywords: ['kangaroo', 'australia', 'jump'] },
      { char: '🦔', name: 'hedgehog', keywords: ['hedgehog', 'prickly', 'cute'] },
      { char: '🐾', name: 'paw prints', keywords: ['paw', 'animal', 'footprint', 'pet'] },
      { char: '🌵', name: 'cactus', keywords: ['cactus', 'desert', 'plant'] },
      { char: '🌲', name: 'evergreen tree', keywords: ['tree', 'forest', 'pine'] },
      { char: '🌳', name: 'deciduous tree', keywords: ['tree', 'nature', 'green'] },
      { char: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical', 'beautiful'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['flower', 'pink', 'spring', 'japan'] },
      { char: '🌼', name: 'blossom', keywords: ['flower', 'spring', 'yellow'] },
      { char: '🌻', name: 'sunflower', keywords: ['sunflower', 'sunny', 'yellow'] },
      { char: '🌹', name: 'rose', keywords: ['rose', 'love', 'romance', 'flower'] },
      { char: '🌷', name: 'tulip', keywords: ['tulip', 'flower', 'spring'] },
      { char: '🍀', name: 'four leaf clover', keywords: ['lucky', 'clover', 'luck'] },
      { char: '🌿', name: 'herb', keywords: ['herb', 'plant', 'green', 'nature'] },
      { char: '🍁', name: 'maple leaf', keywords: ['maple', 'autumn', 'fall', 'canada'] },
      { char: '🌊', name: 'water wave', keywords: ['wave', 'ocean', 'surf', 'sea'] },
      { char: '⭐', name: 'star', keywords: ['star', 'night', 'favorite'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'sparkle', 'shining'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful', 'hope', 'pride'] },
    ]
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍔',
    emojis: [
      { char: '🍎', name: 'red apple', keywords: ['apple', 'fruit', 'red'] },
      { char: '🍊', name: 'tangerine', keywords: ['orange', 'fruit', 'citrus'] },
      { char: '🍋', name: 'lemon', keywords: ['lemon', 'sour', 'citrus', 'yellow'] },
      { char: '🍇', name: 'grapes', keywords: ['grapes', 'fruit', 'wine', 'purple'] },
      { char: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit', 'red'] },
      { char: '🫐', name: 'blueberries', keywords: ['blueberry', 'fruit', 'berries'] },
      { char: '🍒', name: 'cherries', keywords: ['cherry', 'fruit', 'red'] },
      { char: '🍑', name: 'peach', keywords: ['peach', 'fruit', 'butt'] },
      { char: '🍍', name: 'pineapple', keywords: ['pineapple', 'tropical', 'fruit'] },
      { char: '🥭', name: 'mango', keywords: ['mango', 'tropical', 'fruit'] },
      { char: '🥥', name: 'coconut', keywords: ['coconut', 'tropical', 'fruit'] },
      { char: '🍕', name: 'pizza', keywords: ['pizza', 'slice', 'italian', 'cheese'] },
      { char: '🍔', name: 'hamburger', keywords: ['burger', 'hamburger', 'fast food'] },
      { char: '🌮', name: 'taco', keywords: ['taco', 'mexican', 'food'] },
      { char: '🌯', name: 'burrito', keywords: ['burrito', 'wrap', 'mexican'] },
      { char: '🍜', name: 'steaming bowl', keywords: ['noodle', 'ramen', 'soup', 'bowl'] },
      { char: '🍣', name: 'sushi', keywords: ['sushi', 'japanese', 'fish', 'rice'] },
      { char: '🍱', name: 'bento box', keywords: ['bento', 'japanese', 'lunch', 'box'] },
      { char: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'soft serve', 'dessert'] },
      { char: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'celebrate', 'candles'] },
      { char: '🍰', name: 'shortcake', keywords: ['cake', 'dessert', 'sweet'] },
      { char: '🍩', name: 'doughnut', keywords: ['donut', 'doughnut', 'sweet', 'dessert'] },
      { char: '🍪', name: 'cookie', keywords: ['cookie', 'biscuit', 'sweet', 'chocolate chip'] },
      { char: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'sweet', 'candy'] },
      { char: '🍬', name: 'candy', keywords: ['candy', 'sweet', 'sugar'] },
      { char: '🧁', name: 'cupcake', keywords: ['cupcake', 'cake', 'dessert', 'frosting'] },
      { char: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot', 'cup'] },
      { char: '🍵', name: 'teacup without handle', keywords: ['tea', 'hot', 'drink'] },
      { char: '🧃', name: 'beverage box', keywords: ['juice', 'drink', 'box'] },
      { char: '🥤', name: 'cup with straw', keywords: ['drink', 'soda', 'cup', 'straw'] },
      { char: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'cheers', 'pub'] },
      { char: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'cheers', 'celebration'] },
      { char: '🥂', name: 'clinking glasses', keywords: ['champagne', 'toast', 'celebrate', 'cheers'] },
      { char: '🍷', name: 'wine glass', keywords: ['wine', 'drink', 'red wine'] },
      { char: '🧋', name: 'bubble tea', keywords: ['boba', 'bubble tea', 'drink', 'tea'] },
    ]
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { char: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport', 'ball'] },
      { char: '🏀', name: 'basketball', keywords: ['basketball', 'sport', 'ball'] },
      { char: '🏈', name: 'american football', keywords: ['football', 'american', 'sport'] },
      { char: '⚾', name: 'baseball', keywords: ['baseball', 'sport', 'ball'] },
      { char: '🎾', name: 'tennis', keywords: ['tennis', 'sport', 'ball'] },
      { char: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport', 'ball'] },
      { char: '🏒', name: 'ice hockey', keywords: ['hockey', 'ice', 'sport'] },
      { char: '🏓', name: 'ping pong', keywords: ['ping pong', 'table tennis', 'sport'] },
      { char: '🥊', name: 'boxing glove', keywords: ['boxing', 'fight', 'sport', 'punch'] },
      { char: '🥋', name: 'martial arts uniform', keywords: ['karate', 'martial arts', 'sport'] },
      { char: '⛷️', name: 'skier', keywords: ['ski', 'snow', 'winter sport'] },
      { char: '🏊', name: 'person swimming', keywords: ['swim', 'pool', 'sport', 'water'] },
      { char: '🚴', name: 'person biking', keywords: ['bike', 'cycling', 'sport', 'bicycle'] },
      { char: '🏋️', name: 'person lifting weights', keywords: ['gym', 'weights', 'sport', 'workout'] },
      { char: '🧗', name: 'person climbing', keywords: ['climb', 'rock', 'sport'] },
      { char: '🤺', name: 'person fencing', keywords: ['fencing', 'sword', 'sport'] },
      { char: '🏇', name: 'horse racing', keywords: ['horse', 'race', 'sport'] },
      { char: '🤿', name: 'diving mask', keywords: ['dive', 'snorkel', 'ocean'] },
      { char: '🎯', name: 'bullseye', keywords: ['target', 'goal', 'aim', 'bullseye', 'dart'] },
      { char: '🎱', name: 'pool 8 ball', keywords: ['billiards', 'pool', '8 ball'] },
      { char: '🎮', name: 'video game', keywords: ['game', 'gaming', 'controller', 'play'] },
      { char: '🕹️', name: 'joystick', keywords: ['joystick', 'game', 'arcade', 'retro'] },
      { char: '🎲', name: 'game die', keywords: ['dice', 'game', 'chance', 'luck', 'board game'] },
      { char: '♟️', name: 'chess pawn', keywords: ['chess', 'game', 'strategy'] },
      { char: '🎸', name: 'guitar', keywords: ['guitar', 'music', 'rock', 'instrument'] },
      { char: '🎹', name: 'musical keyboard', keywords: ['piano', 'keyboard', 'music'] },
      { char: '🎺', name: 'trumpet', keywords: ['trumpet', 'music', 'instrument'] },
      { char: '🥁', name: 'drum', keywords: ['drum', 'music', 'beat'] },
      { char: '🎤', name: 'microphone', keywords: ['mic', 'sing', 'karaoke', 'voice'] },
      { char: '🎧', name: 'headphone', keywords: ['headphones', 'music', 'listen'] },
      { char: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'creative', 'design'] },
      { char: '🖌️', name: 'paintbrush', keywords: ['paint', 'art', 'brush', 'creative'] },
      { char: '✏️', name: 'pencil', keywords: ['pencil', 'write', 'draw', 'edit'] },
      { char: '📸', name: 'camera with flash', keywords: ['photo', 'camera', 'picture', 'snap'] },
      { char: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'action', 'cinema'] },
      { char: '🎭', name: 'performing arts', keywords: ['theater', 'drama', 'arts'] },
      { char: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'congrats', 'tada'] },
      { char: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate', 'confetti'] },
      { char: '🎈', name: 'balloon', keywords: ['balloon', 'party', 'celebrate'] },
      { char: '🏆', name: 'trophy', keywords: ['trophy', 'win', 'award', 'champion', 'first'] },
      { char: '🥇', name: 'gold medal', keywords: ['gold', 'medal', 'first', 'winner'] },
      { char: '🥈', name: 'silver medal', keywords: ['silver', 'medal', 'second'] },
      { char: '🥉', name: 'bronze medal', keywords: ['bronze', 'medal', 'third'] },
    ]
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { char: '✈️', name: 'airplane', keywords: ['plane', 'fly', 'travel', 'flight'] },
      { char: '🚀', name: 'rocket', keywords: ['rocket', 'space', 'launch', 'fast'] },
      { char: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space', 'flying saucer'] },
      { char: '🚁', name: 'helicopter', keywords: ['helicopter', 'fly', 'air'] },
      { char: '🚂', name: 'locomotive', keywords: ['train', 'locomotive', 'rail'] },
      { char: '🚗', name: 'automobile', keywords: ['car', 'drive', 'vehicle'] },
      { char: '🚕', name: 'taxi', keywords: ['taxi', 'cab', 'car', 'ride'] },
      { char: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car', 'drive'] },
      { char: '🏎️', name: 'racing car', keywords: ['race car', 'fast', 'speed', 'formula'] },
      { char: '🚓', name: 'police car', keywords: ['police', 'cop', 'car', 'law'] },
      { char: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency', 'medical'] },
      { char: '🚒', name: 'fire engine', keywords: ['fire', 'truck', 'engine', 'emergency'] },
      { char: '🚌', name: 'bus', keywords: ['bus', 'transport', 'school bus'] },
      { char: '🚍', name: 'oncoming bus', keywords: ['bus', 'transport'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike', 'cycle', 'bicycle'] },
      { char: '🛴', name: 'kick scooter', keywords: ['scooter', 'kick', 'ride'] },
      { char: '🛵', name: 'motor scooter', keywords: ['scooter', 'moped', 'vespa'] },
      { char: '⛵', name: 'sailboat', keywords: ['sail', 'boat', 'ocean'] },
      { char: '🚢', name: 'ship', keywords: ['ship', 'cruise', 'ocean', 'boat'] },
      { char: '🏠', name: 'house', keywords: ['home', 'house', 'building'] },
      { char: '🏢', name: 'office building', keywords: ['office', 'building', 'work', 'company'] },
      { char: '🏰', name: 'castle', keywords: ['castle', 'kingdom', 'fairy tale', 'medieval'] },
      { char: '🗼', name: 'Tokyo Tower', keywords: ['tower', 'japan', 'tokyo', 'landmark'] },
      { char: '🗽', name: 'Statue of Liberty', keywords: ['statue', 'liberty', 'new york', 'usa'] },
      { char: '🗺️', name: 'world map', keywords: ['map', 'world', 'travel', 'globe'] },
      { char: '🌍', name: 'globe showing Europe-Africa', keywords: ['earth', 'globe', 'world'] },
      { char: '🌎', name: 'globe showing Americas', keywords: ['earth', 'globe', 'world', 'americas'] },
      { char: '🌏', name: 'globe showing Asia-Australia', keywords: ['earth', 'globe', 'world', 'asia'] },
      { char: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'snow', 'peak', 'nature'] },
      { char: '🌋', name: 'volcano', keywords: ['volcano', 'lava', 'eruption'] },
      { char: '🏝️', name: 'desert island', keywords: ['island', 'tropical', 'beach', 'holiday'] },
      { char: '🌅', name: 'sunrise', keywords: ['sunrise', 'morning', 'dawn', 'sun'] },
      { char: '🌃', name: 'night with stars', keywords: ['night', 'stars', 'city', 'evening'] },
      { char: '⛽', name: 'fuel pump', keywords: ['gas', 'fuel', 'pump', 'station'] },
      { char: '🧳', name: 'luggage', keywords: ['luggage', 'travel', 'suitcase', 'trip'] },
    ]
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { char: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb', 'bright', 'think'] },
      { char: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch', 'light'] },
      { char: '💻', name: 'laptop', keywords: ['laptop', 'computer', 'tech', 'work'] },
      { char: '🖥️', name: 'desktop computer', keywords: ['computer', 'desktop', 'monitor', 'tech'] },
      { char: '🖨️', name: 'printer', keywords: ['printer', 'print', 'office'] },
      { char: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type', 'computer'] },
      { char: '🖱️', name: 'computer mouse', keywords: ['mouse', 'computer', 'click'] },
      { char: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'smartphone', 'cell'] },
      { char: '📲', name: 'mobile phone with arrow', keywords: ['phone', 'call', 'download'] },
      { char: '☎️', name: 'telephone', keywords: ['phone', 'telephone', 'call', 'landline'] },
      { char: '📷', name: 'camera', keywords: ['camera', 'photo', 'picture'] },
      { char: '📹', name: 'video camera', keywords: ['video', 'camera', 'record', 'film'] },
      { char: '📺', name: 'television', keywords: ['tv', 'television', 'watch', 'screen'] },
      { char: '📻', name: 'radio', keywords: ['radio', 'broadcast', 'music'] },
      { char: '🔋', name: 'battery', keywords: ['battery', 'power', 'energy', 'charge'] },
      { char: '🔌', name: 'electric plug', keywords: ['plug', 'electric', 'power', 'charge'] },
      { char: '💾', name: 'floppy disk', keywords: ['floppy', 'disk', 'save', 'storage'] },
      { char: '💿', name: 'optical disk', keywords: ['cd', 'disc', 'music', 'data'] },
      { char: '📀', name: 'dvd', keywords: ['dvd', 'disc', 'movie', 'video'] },
      { char: '🔍', name: 'magnifying glass tilted left', keywords: ['search', 'find', 'look', 'magnify'] },
      { char: '🔎', name: 'magnifying glass tilted right', keywords: ['search', 'find', 'zoom'] },
      { char: '🔑', name: 'key', keywords: ['key', 'lock', 'access', 'password'] },
      { char: '🗝️', name: 'old key', keywords: ['key', 'old', 'lock'] },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure', 'locked', 'private'] },
      { char: '🔓', name: 'unlocked', keywords: ['unlock', 'open', 'unlocked'] },
      { char: '🔨', name: 'hammer', keywords: ['hammer', 'tool', 'build'] },
      { char: '⚙️', name: 'gear', keywords: ['gear', 'settings', 'settings', 'tool'] },
      { char: '🔧', name: 'wrench', keywords: ['wrench', 'tool', 'fix', 'repair'] },
      { char: '📎', name: 'paperclip', keywords: ['paperclip', 'attach', 'clip'] },
      { char: '📌', name: 'pushpin', keywords: ['pin', 'pinned', 'location', 'pushpin'] },
      { char: '📍', name: 'round pushpin', keywords: ['pin', 'location', 'map'] },
      { char: '📝', name: 'memo', keywords: ['memo', 'note', 'write', 'reminder'] },
      { char: '📋', name: 'clipboard', keywords: ['clipboard', 'copy', 'paste', 'tasks'] },
      { char: '📁', name: 'file folder', keywords: ['folder', 'files', 'directory'] },
      { char: '📂', name: 'open file folder', keywords: ['folder', 'open', 'files'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'graph', 'data', 'stats'] },
      { char: '📈', name: 'chart increasing', keywords: ['chart', 'graph', 'up', 'growth', 'trending'] },
      { char: '📉', name: 'chart decreasing', keywords: ['chart', 'graph', 'down', 'loss'] },
      { char: '🗓️', name: 'spiral calendar', keywords: ['calendar', 'date', 'schedule'] },
      { char: '📅', name: 'calendar', keywords: ['calendar', 'date', 'schedule'] },
      { char: '⏰', name: 'alarm clock', keywords: ['alarm', 'clock', 'time', 'wake'] },
      { char: '⏱️', name: 'stopwatch', keywords: ['stopwatch', 'time', 'timer'] },
      { char: '⏳', name: 'hourglass not done', keywords: ['hourglass', 'time', 'wait', 'loading'] },
      { char: '⌛', name: 'hourglass done', keywords: ['hourglass', 'time', 'done', 'waiting'] },
      { char: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday', 'surprise'] },
      { char: '🧸', name: 'teddy bear', keywords: ['teddy', 'bear', 'toy', 'cute'] },
      { char: '🔔', name: 'bell', keywords: ['bell', 'notification', 'alert', 'ring'] },
      { char: '🔕', name: 'bell with slash', keywords: ['mute', 'silent', 'no bell', 'off'] },
    ]
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      { char: '❤️', name: 'red heart', keywords: ['heart', 'love', 'red', 'romance'] },
      { char: '🧡', name: 'orange heart', keywords: ['heart', 'orange', 'love'] },
      { char: '💛', name: 'yellow heart', keywords: ['heart', 'yellow', 'love'] },
      { char: '💚', name: 'green heart', keywords: ['heart', 'green', 'love'] },
      { char: '💙', name: 'blue heart', keywords: ['heart', 'blue', 'love'] },
      { char: '💜', name: 'purple heart', keywords: ['heart', 'purple', 'love'] },
      { char: '🖤', name: 'black heart', keywords: ['heart', 'black', 'dark', 'emo'] },
      { char: '🤍', name: 'white heart', keywords: ['heart', 'white', 'pure'] },
      { char: '🤎', name: 'brown heart', keywords: ['heart', 'brown', 'love'] },
      { char: '💔', name: 'broken heart', keywords: ['broken heart', 'heartbreak', 'sad'] },
      { char: '❣️', name: 'heart exclamation', keywords: ['heart', 'exclamation', 'love'] },
      { char: '💕', name: 'two hearts', keywords: ['hearts', 'love', 'couple'] },
      { char: '💞', name: 'revolving hearts', keywords: ['hearts', 'love', 'rotating'] },
      { char: '💓', name: 'beating heart', keywords: ['heart', 'beating', 'love', 'pulse'] },
      { char: '💗', name: 'growing heart', keywords: ['heart', 'growing', 'love'] },
      { char: '💖', name: 'sparkling heart', keywords: ['heart', 'sparkle', 'love', 'bling'] },
      { char: '💘', name: 'heart with arrow', keywords: ['heart', 'arrow', 'cupid', 'love'] },
      { char: '💝', name: 'heart with ribbon', keywords: ['heart', 'ribbon', 'gift', 'love'] },
      { char: '💟', name: 'heart decoration', keywords: ['heart', 'decoration', 'love'] },
      { char: '🔥', name: 'fire', keywords: ['fire', 'hot', 'lit', 'flame', 'burn', 'trending'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkles', 'shine', 'magic', 'glitter', 'star'] },
      { char: '💥', name: 'collision', keywords: ['explosion', 'boom', 'blast', 'impact'] },
      { char: '💢', name: 'anger symbol', keywords: ['angry', 'mad', 'anger', 'comic'] },
      { char: '💨', name: 'dashing away', keywords: ['fast', 'wind', 'dash', 'speed'] },
      { char: '💦', name: 'sweat droplets', keywords: ['sweat', 'water', 'drops', 'splash'] },
      { char: '💫', name: 'dizzy', keywords: ['dizzy', 'star', 'spin', 'sparkle'] },
      { char: '💬', name: 'speech bubble', keywords: ['speech', 'chat', 'talk', 'bubble', 'message'] },
      { char: '💭', name: 'thought balloon', keywords: ['think', 'thought', 'cloud'] },
      { char: '💤', name: 'zzz', keywords: ['sleep', 'zzz', 'tired', 'snore'] },
      { char: '✅', name: 'check mark button', keywords: ['check', 'done', 'yes', 'correct', 'complete'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'error', 'cancel', 'close'] },
      { char: '⚠️', name: 'warning', keywords: ['warning', 'alert', 'caution', 'danger'] },
      { char: '🚫', name: 'prohibited', keywords: ['no', 'banned', 'not allowed', 'forbidden'] },
      { char: '🔴', name: 'red circle', keywords: ['red', 'dot', 'circle', 'stop'] },
      { char: '🟠', name: 'orange circle', keywords: ['orange', 'dot', 'circle'] },
      { char: '🟡', name: 'yellow circle', keywords: ['yellow', 'dot', 'circle'] },
      { char: '🟢', name: 'green circle', keywords: ['green', 'dot', 'circle', 'go'] },
      { char: '🔵', name: 'blue circle', keywords: ['blue', 'dot', 'circle'] },
      { char: '⭐', name: 'star', keywords: ['star', 'favorite', 'rate', 'bookmark'] },
      { char: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score', 'excellent'] },
      { char: '🆕', name: 'new button', keywords: ['new', 'badge', 'fresh'] },
      { char: '🆙', name: 'up button', keywords: ['up', 'upgrade', 'update'] },
      { char: '🔝', name: 'top arrow', keywords: ['top', 'up', 'arrow'] },
      { char: '🔛', name: 'on arrow', keywords: ['on', 'switch'] },
      { char: '🔜', name: 'soon arrow', keywords: ['soon', 'coming'] },
      { char: '#️⃣', name: 'keycap number sign', keywords: ['hash', 'number', 'hashtag', 'pound'] },
      { char: '©️', name: 'copyright', keywords: ['copyright', 'legal', 'rights'] },
      { char: '®️', name: 'registered', keywords: ['registered', 'trademark', 'legal'] },
      { char: '™️', name: 'trade mark', keywords: ['trademark', 'tm', 'brand'] },
    ]
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏁',
    emojis: [
      { char: '🏁', name: 'chequered flag', keywords: ['race', 'finish', 'flag', 'checkered'] },
      { char: '🚩', name: 'triangular flag', keywords: ['flag', 'red flag', 'warning', 'mark'] },
      { char: '🎌', name: 'crossed flags', keywords: ['japan', 'crossed', 'flags'] },
      { char: '🏴', name: 'black flag', keywords: ['black', 'flag', 'pirate'] },
      { char: '🏳️', name: 'white flag', keywords: ['white', 'flag', 'surrender', 'peace'] },
      { char: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'lgbtq', 'rainbow', 'flag', 'gay'] },
      { char: '🏳️‍⚧️', name: 'transgender flag', keywords: ['trans', 'transgender', 'pride', 'flag'] },
      { char: '🏴‍☠️', name: 'pirate flag', keywords: ['pirate', 'skull', 'jolly roger', 'flag'] },
      { char: '🇺🇸', name: 'flag United States', keywords: ['usa', 'america', 'united states', 'flag'] },
      { char: '🇬🇧', name: 'flag United Kingdom', keywords: ['uk', 'britain', 'england', 'flag'] },
      { char: '🇨🇦', name: 'flag Canada', keywords: ['canada', 'flag', 'maple'] },
      { char: '🇦🇺', name: 'flag Australia', keywords: ['australia', 'flag', 'aussie'] },
      { char: '🇩🇪', name: 'flag Germany', keywords: ['germany', 'german', 'flag'] },
      { char: '🇫🇷', name: 'flag France', keywords: ['france', 'french', 'flag', 'paris'] },
      { char: '🇯🇵', name: 'flag Japan', keywords: ['japan', 'japanese', 'flag'] },
      { char: '🇨🇳', name: 'flag China', keywords: ['china', 'chinese', 'flag'] },
      { char: '🇮🇳', name: 'flag India', keywords: ['india', 'indian', 'flag'] },
      { char: '🇧🇷', name: 'flag Brazil', keywords: ['brazil', 'brazilian', 'flag'] },
      { char: '🇿🇦', name: 'flag South Africa', keywords: ['south africa', 'flag'] },
      { char: '🇸🇦', name: 'flag Saudi Arabia', keywords: ['saudi arabia', 'flag', 'arab'] },
      { char: '🇦🇪', name: 'flag UAE', keywords: ['uae', 'emirates', 'dubai', 'flag'] },
      { char: '🇪🇬', name: 'flag Egypt', keywords: ['egypt', 'flag'] },
      { char: '🇲🇾', name: 'flag Malaysia', keywords: ['malaysia', 'flag'] },
      { char: '🇸🇬', name: 'flag Singapore', keywords: ['singapore', 'flag'] },
      { char: '🇵🇭', name: 'flag Philippines', keywords: ['philippines', 'flag', 'pilipinas'] },
      { char: '🇮🇩', name: 'flag Indonesia', keywords: ['indonesia', 'flag'] },
      { char: '🇳🇬', name: 'flag Nigeria', keywords: ['nigeria', 'flag'] },
      { char: '🇲🇽', name: 'flag Mexico', keywords: ['mexico', 'mexican', 'flag'] },
      { char: '🇦🇷', name: 'flag Argentina', keywords: ['argentina', 'flag'] },
      { char: '🇹🇷', name: 'flag Turkey', keywords: ['turkey', 'flag'] },
    ]
  }
];

// ─── Sticker Packs ───────────────────────────────────────────────────────────

export const STICKER_PACKS: StickerPack[] = [
  {
    id: 'reactions',
    label: 'Reactions',
    icon: '👍',
    stickers: [
      { char: '👍', name: 'thumbs up', keywords: ['like', 'approve', 'yes', 'good'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad'] },
      { char: '❤️', name: 'red heart', keywords: ['love', 'heart', 'like'] },
      { char: '🔥', name: 'fire', keywords: ['fire', 'hot', 'lit', 'flame'] },
      { char: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'excellent'] },
      { char: '✅', name: 'check mark', keywords: ['done', 'yes', 'correct', 'complete'] },
      { char: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'cancel'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'funny', 'lol'] },
      { char: '😍', name: 'heart eyes', keywords: ['love', 'amazing', 'beautiful'] },
      { char: '🤩', name: 'star struck', keywords: ['wow', 'amazing', 'star'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'pondering'] },
      { char: '😮', name: 'surprised face', keywords: ['wow', 'surprised', 'shock'] },
      { char: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
      { char: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks'] },
      { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'power'] },
      { char: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'congrats'] },
    ]
  },
  {
    id: 'fun',
    label: 'Fun & Memes',
    icon: '🎊',
    stickers: [
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday', 'woo'] },
      { char: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked', 'amazing'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'dying', 'lol', 'funny'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'laugh', 'funny'] },
      { char: '🤡', name: 'clown face', keywords: ['clown', 'joker', 'silly'] },
      { char: '👻', name: 'ghost', keywords: ['ghost', 'spooky', 'boo', 'halloween'] },
      { char: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito', 'spy'] },
      { char: '🫡', name: 'saluting face', keywords: ['salute', 'respect', 'sir'] },
      { char: '🤌', name: 'pinched fingers', keywords: ['perfection', 'chef kiss', 'italian'] },
      { char: '💅', name: 'nail polish', keywords: ['nails', 'fancy', 'glamour', 'unbothered'] },
      { char: '🫣', name: 'face with peeking eye', keywords: ['peek', 'hide', 'nervous', 'shy'] },
      { char: '🙈', name: 'see no evil', keywords: ['monkey', 'see no evil', 'ignore'] },
      { char: '🤪', name: 'zany face', keywords: ['crazy', 'wild', 'silly', 'fun'] },
      { char: '😈', name: 'devil', keywords: ['devil', 'evil', 'mischief', 'naughty'] },
      { char: '👾', name: 'alien monster', keywords: ['game', 'alien', 'monster', 'retro'] },
      { char: '🚨', name: 'siren', keywords: ['alert', 'alarm', 'emergency', 'police'] },
    ]
  },
  {
    id: 'work',
    label: 'Work & Office',
    icon: '💼',
    stickers: [
      { char: '💼', name: 'briefcase', keywords: ['work', 'office', 'business', 'job'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'graph', 'data', 'stats', 'metrics'] },
      { char: '📈', name: 'chart increasing', keywords: ['growth', 'up', 'trending', 'progress'] },
      { char: '💡', name: 'light bulb', keywords: ['idea', 'bright', 'innovation', 'think'] },
      { char: '🚀', name: 'rocket', keywords: ['launch', 'ship it', 'fast', 'go'] },
      { char: '🏆', name: 'trophy', keywords: ['win', 'winner', 'champion', 'award'] },
      { char: '🎯', name: 'bullseye', keywords: ['target', 'goal', 'aim', 'deadline'] },
      { char: '✔️', name: 'check mark', keywords: ['done', 'complete', 'checked', 'finished'] },
      { char: '📋', name: 'clipboard', keywords: ['tasks', 'todo', 'list', 'plan'] },
      { char: '⏰', name: 'alarm clock', keywords: ['deadline', 'time', 'alarm', 'schedule'] },
      { char: '🔑', name: 'key', keywords: ['key', 'access', 'unlock', 'important'] },
      { char: '💻', name: 'laptop', keywords: ['work', 'code', 'computer', 'tech'] },
      { char: '📧', name: 'e-mail', keywords: ['email', 'mail', 'message', 'inbox'] },
      { char: '📞', name: 'telephone receiver', keywords: ['call', 'phone', 'call me'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'agreement', 'partners'] },
      { char: '⭐', name: 'star', keywords: ['star', 'favorite', 'rate', 'review'] },
    ]
  },
  {
    id: 'vibes',
    label: 'Vibes',
    icon: '✨',
    stickers: [
      { char: '✨', name: 'sparkles', keywords: ['magic', 'sparkle', 'glitter', 'shine'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'shine', 'amazing', 'bright'] },
      { char: '💖', name: 'sparkling heart', keywords: ['love', 'heart', 'sparkle', 'cute'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful', 'hope', 'beautiful'] },
      { char: '😎', name: 'cool sunglasses', keywords: ['cool', 'awesome', 'chill'] },
      { char: '🥰', name: 'smiling with hearts', keywords: ['love', 'adore', 'cute', 'heart'] },
      { char: '🤗', name: 'hugging face', keywords: ['hug', 'warm', 'friendly', 'embrace'] },
      { char: '😌', name: 'relieved face', keywords: ['chill', 'calm', 'peaceful', 'slay'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise', 'hands up', 'yes'] },
      { char: '💫', name: 'dizzy star', keywords: ['sparkle', 'star', 'spin', 'dazed'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'pink', 'bloom'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly', 'transform', 'beautiful'] },
      { char: '🌊', name: 'ocean wave', keywords: ['wave', 'ocean', 'chill', 'surf'] },
      { char: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'bright', 'happy', 'morning'] },
      { char: '🌙', name: 'crescent moon', keywords: ['moon', 'night', 'sleep', 'vibe'] },
      { char: '🎶', name: 'musical notes', keywords: ['music', 'song', 'notes', 'melody'] },
    ]
  }
];

// ─── Search Index ─────────────────────────────────────────────────────────────

export function buildEmojiSearchIndex(): Map<string, EmojiEntry[]> {
  const index = new Map<string, EmojiEntry[]>();
  for (const cat of EMOJI_CATEGORIES) {
    for (const emoji of cat.emojis) {
      const terms = [emoji.name, ...emoji.keywords];
      for (const term of terms) {
        const words = term.toLowerCase().split(/\s+/);
        for (const word of words) {
          if (!index.has(word)) index.set(word, []);
          index.get(word)!.push(emoji);
        }
      }
    }
  }
  return index;
}

export function buildStickerSearchIndex(): Map<string, StickerEntry[]> {
  const index = new Map<string, StickerEntry[]>();
  for (const pack of STICKER_PACKS) {
    for (const sticker of pack.stickers) {
      const terms = [sticker.name, ...sticker.keywords];
      for (const term of terms) {
        const words = term.toLowerCase().split(/\s+/);
        for (const word of words) {
          if (!index.has(word)) index.set(word, []);
          index.get(word)!.push(sticker);
        }
      }
    }
  }
  return index;
}
